services:
  compiler:
    build:
      context: .
    tty: true
    command: tail -F /dev/null
    volumes:
      - ./:/root/app
    # to allow vscode connect to gdb:
    cap_add:
      - SYS_PTRACE
    
    